services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:stable
    ports: ["8550:8545"]
    entrypoint:
      [
        "anvil",
        "--fork-url",
        "https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}",
        "--host",
        "0.0.0.0",
        "--silent",
        "--hardfork",
        "prague"
      ]
    platform: linux/arm64
    healthcheck:
      test: ["CMD-SHELL", "cast rpc web3_clientVersion | grep -c anvil > /dev/null "]
      start_interval: 250ms
      start_period: 10s
      interval: 30s
      timeout: 5s
      retries: 10

  contract-deployer:
    image: ghcr.io/pimlicolabs/mock-contract-deployer:main
    environment:
      - ANVIL_RPC=http://anvil:8545
      - SKIP_DEPLOYMENTS=true
    depends_on:
      anvil:
        condition: service_healthy

  mock-paymaster:
    image: ghcr.io/pimlicolabs/mock-verifying-paymaster:main
    platform: linux/arm64
    restart: always
    ports: ["3000:3000"]
    environment:
      - ALTO_RPC=http://alto:4337
      - ANVIL_RPC=http://anvil:8545
    depends_on:
      contract-deployer:
        condition: service_completed_successfully

  alto:
    image: ghcr.io/pimlicolabs/alto:latest
    platform: linux/arm64
    expose: ["4337"]
    environment:
      - ANVIL_RPC=http://anvil:8545
    entrypoint: ["node", "src/lib/cli/alto.js", "run", "--config", "/app/alto-config.json"]
    volumes:
      - ./alto-config.json:/app/alto-config.json
    depends_on:
      contract-deployer:
        condition: service_completed_successfully

  alto-proxy:
    image: nginx:1.27.5-bookworm
    platform: linux/arm64
    ports: ["4337:80"]
    volumes:
      - ./alto-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - alto
